{{ config(materialized='table') }}

SELECT
    gid as "ID",
    nom as "Centre",
    arrete_pref_numero as "Arrêté prefectoral",
    xy_precis as "Coordonnées",
    id_adr as "ID adresse",
    adr_num as "Numéro voie",
    adr_voie as "Nom voie",
    com_cp as "Code postal",
    com_insee as "Code INSEE",
    com_nom as "Ville",
    lat_coor1 as "Latitude",
    long_coor1 as "Longitude",
    structure_siren as "SIREN",
    structure_type as "Code APE",
    structure_rais as "Agence santé",
    structure_num as "AS - Num voie",
    structure_voie as "AS - Nom voie",
    structure_cp as "AS - Code postal",
    structure_insee as "AS - Code INSEE",
    structure_com as "AS - Ville",
    _userid_creation as "user create",
    _userid_modification as "user last modif",
    _edit_datemaj as "Date dernière MAJ",
    lieu_accessibilite as "Accessibilite",
    rdv_lundi as "Ouvert lundi",
    rdv_mardi as "Ouvert mardi",
    rdv_mercredi as "Ouvert mercredi",
    rdv_jeudi as "Ouvert jeudi",
    rdv_vendredi as "Ouvert vendredi",
    rdv_samedi as "Ouvert samedi",
    rdv_dimanche as "Ouvert dimanche",
    rdv as "RDV",
    date_fermeture as "Date fermeture centre",
    date_ouverture as "Date ouverture centre",
    rdv_site_web as "Site résa",
    rdv_tel as "Téléphone",
    rdv_tel2 as "Téléphone 2",
    rdv_modalites as "Modalité",
    rdv_consultation_prevaccination as "Consultation pré vax",
    centre_svi_repondeur as "Répondeur",
    centre_fermeture as "Still open",
    reserve_professionels_sante as "Réservé prof de santé",
    centre_type as "Type de centre"
FROM {{ source('raw', 'CENTRES_VACCINATIONS') }}