select
    ID_CENTRE,
    DATE_DEBUT_SEMAINE,
    CODE_REGION,
    NOM_REGION,
    CODE_DEPARTEMENT,
    NOM_DEPARTEMENT,
    COMMUNE_INSEE,
    NOM_CENTRE,
    NOMBRE_UCD,
    DOSES_ALLOUEES,
    RDV_PRIS
from PC_DBT_DB.DBT_JPRUGNIAUD.ALLOCATIONS_VS_RDV