{{ config(materialized='table') }}
select
    CODE_COMMUNE_INSEE,
    NOM_COMMUNE_POSTAL,
    CODE_POSTAL,
    LIBELLE_ACHEMINEMENT,
    LIGNE_5,
    LATITUDE,
    LONGITUDE,
    CODE_COMMUNE,
    ARTICLE,
    NOM_COMMUNE,
    NOM_COMMUNE_COMPLET,
    CODE_DEPARTEMENT,
    NOM_DEPARTEMENT,
    CODE_REGION,
    NOM_REGION
from {{ source('raw','DIM_FRANCE_REG_DPT_ZIP')}}