select
    CODE_REGION,
    REGION,
    DEPARTEMENT,
    ID_CENTRE,
    NOM_CENTRE,
    RANG_VACCINAL,
    DATE_DEBUT_SEMAINE,
    NB,
    NB_RDV_CNAM,
    NB_RDV_RAPPEL
from PC_DBT_DB.DBT_JPRUGNIAUD.PRISE_RDV_PAR_CENTRE